apiVersion: apps/v1
kind: Deployment
metadata:
  name: taska2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: taska2
  template:
    metadata:
      labels:
        app: taska2
    spec:
      containers:
      - name: taska2
        image: nginx
        ports:
        - containerPort: 80